DDCE-5157 : Toggle images + code cleanup
hmrc/binding-tariff-ruling-frontend pull request #110
Opened 2023-12-19 16:38 UTC by lmugnai

2023-12-20 13:10 UTC, EdCope requested changes
Works and presume for this initial fix we don't need to cover [these end points](https://github.com/hmrc/binding-tariff-ruling-frontend/blob/509370e63f447aaa72599ae45cf908fee6404c56/conf/app.routes#L16-L17) as they are still accessible should you have the id.

This following acceptance test will need reviewing for the flag state.

https://github.com/hmrc/digital-tariffs-acceptance-tests/blob/f3c226a8aeedaabdae81a995c039ec258f44f14f/src/test/resources/features/rulings-ui/PublicRulingsSearch.feature#L32

2023-12-20 14:11 UTC, lmugnai commented on test/unit/uk/gov/hmrc/bindingtariffrulingfrontend/views/RulingViewSpec.scala
> +          given(appConfig.displayImages) willReturn false
Let's use given here for now as it's used a lot in this repo. If we want to change this let's have a ticket to refactor all.

2023-12-20 14:33 UTC, lmugnai commented on app/uk/gov/hmrc/bindingtariffrulingfrontend/workers/RulingsWorker.scala
> -  val LocalDateFormatter: DateTimeFormatter = DateTimeFormatter.ISO_LOCAL_DATE
Done

2023-12-20 14:33 UTC, lmugnai commented on project/plugins.sbt
>  addSbtPlugin("com.beautiful-scala" % "sbt-scalastyle"           % "1.5.1")
Done

2023-12-21 12:52 UTC, EdCope approved these changes

2023-12-21 12:52 UTC, merged