[DDCE-3550] Scala 2.13.10 upgrade + others
hmrc/binding-tariff-ruling-frontend pull request #96
Opened 2023-02-20 13:38 UTC by Nboaram

2023-02-22 14:42 UTC, EdCope requested changes
Optimise imports for:-
AuditServiceSpec
AttachmentControllerSpec
ImageControllerSpec
SearchControllerSpec

2023-02-22 14:42 UTC, EdCope commented on build.sbt
>    .settings(scalaSettings: _*)
These can be removed along with [line](https://github.com/hmrc/binding-tariff-ruling-frontend/blob/main/build.sbt#L9) `lazy val playSettings: Seq[Setting[_]] = Seq.empty`

2023-02-23 11:32 UTC, Nboaram commented on project/build.properties
> +sbt.version=1.8.0
for this one, I'm already having to mess with the scala-xml version because of Scala 2.13 anyway. So can it not just be left at 1.8.0?

2023-02-23 11:44 UTC, EdCope commented on project/build.properties
> +sbt.version=1.8.0
Yeh it is probably fine, can't see why it would cause an issue. Just letting you know what I'm following currently.

2023-02-23 12:36 UTC, EdCope approved these changes

2023-02-23 12:37 UTC, merged